---
- name: Install Grafana and prometheus on bastion
  hosts: bastion
  gather_facts: true
  become: true
  tasks:
    - name: Update apt repo and cache on all Ubuntu box
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install required packages
      apt:
        name:
          - gnupg2
          - curl
          - software-properties-common

    - name: Add the Grafana GPG key
      shell: |
        curl https://packages.grafana.com/gpg.key | sudo apt-key add -
        add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
      args:
        warn: no

    - name: Install the grafana package
      apt:
        name: grafana
        state: present
        update_cache: yes
      notify:
        - Start grafana
        - Enable grafana

    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
      notify: Start and Enable Nginx

    - name: Create grafana nginx config file
      copy:
          dest: /etc/nginx/conf.d/grafana.conf
          mode: 0755
          content: |
            server {
              listen 80;
              server_tokens off;
              client_max_body_size 10M;
              server_name grafana1.citizix.com;

              ignore_invalid_headers off;

              if ($host !~* ^(grafana1.citizix.com)$ ) {
                  return 444;
              }

              location / {
                  send_timeout            600;
                  proxy_read_timeout      600;
                  proxy_send_timeout      600;
                  proxy_connect_timeout   600;
                  proxy_redirect          off;
                  proxy_set_header        Host $host;
                  proxy_set_header        X-Real-IP $remote_addr;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header        X-Forwarded-Host $server_name;
                  proxy_set_header        X-Forwarded-Proto $scheme;
                  proxy_pass http://127.0.0.1:3000;
              }
            }
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: true

  handlers:
    - name: Start grafana
      systemd:
        name: grafana-server
        state: started

    - name: Enable grafana
      systemd:
        name: grafana-server
        enabled: yes

    - name: Start and Enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
